#ifndef TIG_TIG_H_
#define TIG_TIG_H_

#include "tig/art.h"
#include "tig/bmp.h"
#include "tig/bsearch.h"
#include "tig/button.h"
#include "tig/color.h"
#include "tig/core.h"
#include "tig/debug.h"
#include "tig/draw.h"
#include "tig/dxinput.h"
#include "tig/file.h"
#include "tig/file_cache.h"
#include "tig/find_file.h"
#include "tig/font.h"
#include "tig/idxtable.h"
#include "tig/kb.h"
#include "tig/memory.h"
#include "tig/menu.h"
#include "tig/message.h"
#include "tig/mouse.h"
#include "tig/movie.h"
#include "tig/net.h"
#include "tig/net_blacklist.h"
#include "tig/net_xfer.h"
#include "tig/palette.h"
#include "tig/rect.h"
#include "tig/sound.h"
#include "tig/str_parse.h"
#include "tig/timer.h"
#include "tig/video.h"
#include "tig/window.h"

#endif /* TIG_TIG_H_ */
