name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

defaults:
  run:
    shell: bash

jobs:
  code-format:
    name: Code format check
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: clang-format
        run: find example first_party include src test -type f -name \*.c -o -name \*.cc -o -name \*.h | xargs clang-format --dry-run --Werror

  ios:
    name: iOS
    runs-on: macos-13

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: out/build/ios
          key: ios-cmake-v1

      - name: Configure
        run: cmake --preset ios

      - name: Build
        run: cmake --build --preset ios-debug

  linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Dependencies
        run: |
          sudo apt update
          sudo apt install libx11-dev libxext-dev libxrandr-dev libxi-dev libxinerama-dev libxcursor-dev

      - name: Cache
        uses: actions/cache@v4
        with:
          path: out/build/linux-x64-debug
          key: linux-x64-cmake-v1

      - name: Configure
        run: cmake --preset linux-x64-debug

      - name: Build
        run: cmake --build --preset linux-x64-debug

      - name: Test
        run: ctest --preset linux-x64

  macos:
    name: macOS
    runs-on: macos-13

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: out/build/macos
          key: macos-cmake-v1

      - name: Configure
        run: cmake --preset macos

      - name: Build
        run: cmake --build --preset macos-debug

  windows:
    name: Windows (${{ matrix.arch }})
    runs-on: windows-2025

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86
            generator-platform: Win32
          - arch: x64
            generator-platform: x64

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: out/build/windows-${{ matrix.arch }}
          key: windows-${{ matrix.arch }}-cmake-v2

      - name: Configure
        run: |
          cmake --preset windows-${{ matrix.arch }} \
            -D TIG_BUILD_TESTS=ON \
            -D TIG_BUILD_EXAMPLE=ON \
            # EOL

      - name: Build
        run: |
          cmake --build --preset windows-${{ matrix.arch }}-debug

      - name: Test
        run: ctest --preset windows-${{ matrix.arch }}
